CREATE SEQUENCE IF NOT EXISTS bankaccounts_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS operations_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE users (
                       id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       login     VARCHAR(255)                             NOT NULL,
                       name      VARCHAR(255)                             NOT NULL,
                       age       INTEGER                                  NOT NULL,
                       sex       VARCHAR(255)                             NOT NULL,
                       haircolor VARCHAR(255),
                       CONSTRAINT users_pkey PRIMARY KEY (id),
                       CONSTRAINT users_login_key UNIQUE (login)
);

CREATE TABLE bankaccounts (
                              id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              balance    DOUBLE PRECISION                         NOT NULL,
                              userlogin  VARCHAR(255)                             NOT NULL,
                              user_id    INTEGER                                  NOT NULL,
                              CONSTRAINT bankaccounts_pkey PRIMARY KEY (id),
                              CONSTRAINT bankaccounts_userid_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE operations (
                            id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            account_id INTEGER                                  NOT NULL,
                            type       VARCHAR(255)                             NOT NULL,
                            amount     DOUBLE PRECISION                         NOT NULL,
                            CONSTRAINT operations_pkey PRIMARY KEY (id),
                            CONSTRAINT operations_accountid_fkey FOREIGN KEY (account_id) REFERENCES bankaccounts (id) ON DELETE NO ACTION
);

CREATE TABLE friends (
                         user_id   INTEGER NOT NULL,
                         friend_id INTEGER NOT NULL,
                         CONSTRAINT friends_pkey PRIMARY KEY (user_id, friend_id),
                         CONSTRAINT friends_userid_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION,
                         CONSTRAINT friends_friendid_fkey FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE NO ACTION
);
