CREATE SEQUENCE IF NOT EXISTS bankaccounts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS operations_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE bankaccounts
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance   DOUBLE PRECISION                         NOT NULL,
    userlogin VARCHAR(255)                             NOT NULL,
    userid    INTEGER                                  NOT NULL,
    CONSTRAINT bankaccounts_pkey PRIMARY KEY (id)
);

CREATE TABLE friends
(
    userid   INTEGER NOT NULL,
    friendid INTEGER NOT NULL,
    CONSTRAINT friends_pkey PRIMARY KEY (userid, friendid)
);

CREATE TABLE operations
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    accountid INTEGER                                  NOT NULL,
    type      VARCHAR(255)                             NOT NULL,
    amount    DOUBLE PRECISION                         NOT NULL,
    CONSTRAINT operations_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login     VARCHAR(255)                             NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    age       INTEGER                                  NOT NULL,
    sex       VARCHAR(255)                             NOT NULL,
    haircolor VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT users_login_key UNIQUE (login);

ALTER TABLE bankaccounts
    ADD CONSTRAINT bankaccounts_userid_fkey FOREIGN KEY (userid) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE friends
    ADD CONSTRAINT friends_friendid_fkey FOREIGN KEY (friendid) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE friends
    ADD CONSTRAINT friends_userid_fkey FOREIGN KEY (userid) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE operations
    ADD CONSTRAINT operations_accountid_fkey FOREIGN KEY (accountid) REFERENCES bankaccounts (id) ON DELETE NO ACTION;