spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaLabsDb
    username: postgres
    password: limosha
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true